#!/usr/bin/env python3
"""TEMPLATE — a LESSON that teaches a topic across sections (generated by marimo-teach-topic).

Copy this next to `interactive.py` (from marimo-teach-topic), the borrowed lens helpers
(`excalidraw_scene.py`, `markmap_html.py`, `mermaid_tools.py` from
marimo-visual-explanation), and — ONLY if the user asked for quizzes — `quiz.py`.

Then:
  1. Fill the objectives and roadmap.
  2. Write one SECTION per subtopic at the target DEPTH (default medium): for each
     load-bearing concept answer what it does / what it talks to and does NOT /
     how / the misconception. Carry it with the lens that fits and the interactive
     lenses that make it live (stepper step-through, deep_dive fold, tangle).
  3. DUPLICATE a section block per subtopic. Scale count to breadth, detail to
     depth (see SKILL.md + references/lesson-design.md).
  4. Recap at the end.
  5. Checks are OFF by default — add the optional quiz block ONLY if asked.

marimo gotcha: every top-level variable name must be UNIQUE across all cells
(each stepper/tangle/question its own name). Prefix throwaways with `_`.
"""
import marimo

app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell
def _():
    import os
    import sys
    _here = os.path.dirname(os.path.abspath(__file__))
    if _here not in sys.path:
        sys.path.insert(0, _here)
    from excalidraw_scene import Scene                       # borrowed: spatial lens
    from markmap_html import markmap_html                    # borrowed: mind map
    from interactive import (                                # own: interactive lenses
        deep_dive, stepper, play_stepper, mermaid_at, tangle, key_fact, references,
    )
    from wigglystuff import Excalidraw    # import ONCE here (a lesson has many scenes)
    return (
        Excalidraw, Scene, deep_dive, key_fact, markmap_html,
        mermaid_at, play_stepper, references, stepper, tangle,
    )


@app.cell
def _(mo):
    mo.md(
        """
        # 📚 <!-- >>> FILL: the topic -->

        **What you'll learn** <!-- 2-4 objectives -->
        - <!-- objective 1 -->
        - <!-- objective 2 -->
        - <!-- objective 3 -->

        *~<!-- N --> sections, about <!-- M --> minutes, explained in depth.*
        """
    )
    return


@app.cell
def _(markmap_html, mo):
    # ROADMAP up front — orient the learner before diving in (the map LEADS in a
    # lesson).  >>> FILL with the real sections.
    _roadmap = """
    # <!-- topic -->
    ## <!-- section 1 -->
    ## <!-- section 2 -->
    ## <!-- section 3 -->
    """
    mo.iframe(markmap_html(_roadmap, height=340), height="360px")
    return


# ===================== SECTION 1 — Excalidraw anatomy lens =====================
@app.cell
def _(mo):
    mo.md(
        """
        ## 1. <!-- >>> FILL: section title -->

        <!-- Explain at the target depth. For each load-bearing part: what it does,
        what it talks to AND what it does NOT, how (a step or two), the
        misconception. The prose leads; the diagram supports. -->
        """
    )
    return


@app.cell
def _(Excalidraw, Scene, mo):
    # Excalidraw = the spatial/anatomy story: components, how they're wired, grouped
    # into zones. Freestyle up to ~20 boxes; grid layout (col=/row=).  >>> FILL.
    _sc = Scene(title="<!-- what this shows -->")
    _a = _sc.box("<!-- part 1 -->", col=0, row=0, color="blue", subtitle="<!-- role -->")
    _b = _sc.box("<!-- part 2 -->", col=1, row=0, color="green", subtitle="<!-- role -->")
    _c = _sc.box("<!-- part 3 -->", col=1, row=1, color="yellow", subtitle="<!-- role -->")
    _sc.arrow(_a, _b, label="<!-- verb -->")
    _sc.arrow(_b, _c, label="<!-- verb -->")
    _sc.zone([_a, _b], label="<!-- group -->")
    _sc.note("<!-- the one caveat worth flagging -->", near=_c)
    # fitted() opens the scene zoomed-to-fit AND returns a snug pane height (the
    # widget won't do either) — no empty band, diagram fills the pane.
    # view_w MUST match the app's content column: width="medium" (this template)
    # is 1110px -> pass 1060. Passing 700 fits the scene into ~60% of the column
    # (wide-but-short, tiny). Use 700 only for compact/normal apps.
    # (A compact undo/redo toolbar with no zoom is Excalidraw reacting to a zoomed-in
    #  browser page, not this setting -- zoom the page back out.)
    _scene, _h = _sc.fitted(view_w=1060)
    mo.ui.anywidget(Excalidraw(scene=_scene, height=_h))
    return


@app.cell
def _(mo, references):
    # Anchor the section in authoritative sources — a fold, so it stays out of the
    # way. Use REAL, current URLs for the topic.  >>> FILL.
    references(mo, [
        ("<!-- official docs page -->", "<!-- https://... -->"),
        ("<!-- spec or canonical post -->", "<!-- https://... -->"),
    ])
    return


# ============ SECTION 2 — step-through a process (stepper + mo.mermaid) ========
@app.cell
def _(mo):
    mo.md(
        """
        ## 2. <!-- >>> FILL: a process worth watching unfold -->

        <!-- Explain the process. Then let the reader scrub through it below. -->
        """
    )
    return


@app.cell
def _(mo, stepper):
    # CONTROL cell — unique name.  >>> set N = number of stages.
    s2_step = stepper(mo, 3, label="<!-- e.g. Request step -->")
    s2_step
    return (s2_step,)


@app.cell
def _(mermaid_at, mo, s2_step):
    # VIEW cell — re-runs as the slider moves. Each stage is a full Mermaid string,
    # usually additive (one more hop per step). Keep label text plain ASCII.  >>> FILL.
    _stages = [
        "sequenceDiagram\n    participant A as <!-- x -->\n    participant B as <!-- y -->",
        "sequenceDiagram\n    participant A as <!-- x -->\n    participant B as <!-- y -->\n    A->>B: <!-- step 1 -->",
        "sequenceDiagram\n    participant A as <!-- x -->\n    participant B as <!-- y -->\n    A->>B: <!-- step 1 -->\n    B-->>A: <!-- step 2 -->",
    ]
    mermaid_at(mo, _stages, s2_step.value)
    return


# ====== SECTION 3 — depth on demand (deep_dive) + a what-if (tangle) ==========
@app.cell
def _(mo):
    mo.md(
        """
        ## 3. <!-- >>> FILL: section title -->

        <!-- The medium-depth explanation lives here in the main line. -->
        """
    )
    return


@app.cell
def _(deep_dive, mo):
    # COMPLETE-depth detail tucked behind a fold — a skimmer skips it, a deep
    # reader opens it. Put internals / edge cases / a worked example here.  >>> FILL.
    deep_dive(mo, "<!-- go-deeper title -->",
              "<!-- the mechanism in detail: data structures, phases, the exact "
              "object written, a worked example. -->")
    return


@app.cell
def _(mo, tangle):
    # Optional what-if: an inline draggable number. Delete if the section has no
    # quantitative knob.  >>> FILL or remove.
    s3_knob = tangle(mo, 50, 0, 100, suffix="%")
    mo.hstack([mo.md("If <!-- assumption --> is "), s3_knob, mo.md(" ...")], gap=0)
    return (s3_knob,)


@app.cell
def _(mo, s3_knob):
    mo.md(f"...then <!-- consequence --> is about **{s3_knob.amount:.0f} <!-- unit -->**.")
    return
# =============================================================================


@app.cell
def _(mo):
    mo.md(
        """
        ## Recap

        <!-- 3-5 bullets: the through-line of what was covered. -->

        **Go deeper:** <!-- pointers / next lesson -->
        """
    )
    return


# ============================ OPTIONAL: quizzes ==============================
# Checks are OFF by default. ONLY if the user asked ("quiz me", "with checks"):
#   1. also `cp .../marimo-teach-topic/scripts/quiz.py` next to this file,
#   2. add `from quiz import mcq, check, reveal` to the imports cell,
#   3. add blocks like the two below every few sections (unique q<N>_pick names):
#
#   @app.cell
#   def _(mcq, mo):
#       q1_pick = mcq(mo, "load-bearing question?", ["a", "correct", "c"])
#       q1_pick
#       return (q1_pick,)
#
#   @app.cell
#   def _(check, mo, q1_pick):
#       check(mo, q1_pick.value, "correct",
#             "why it's right; a wrong answer should still learn from this.")
#       return
# =============================================================================


if __name__ == "__main__":
    app.run()
